Workflows
LukasStrickler/FixMyTown pull request #55
Opened 2024-11-22 10:55 UTC by sternlis

#17

2024-11-25 13:35 UTC, LukasStrickler requested changes
pls adjust and also see requests from @joscha-st @Timbo003 @paulKlarer

2024-11-25 13:35 UTC, LukasStrickler commented on docs/workflows/abmelde-prozess.excalidraw
Es gibt keinen "Prozess" dafür, das passiert automatisch durch das system falls die session invalide ist
-> remove workflow oder nur die Warnmeldung

2024-11-25 13:35 UTC, LukasStrickler commented on docs/workflows/archivierungsprozess.excalidraw
Was ist hier genau gemeint ? Bilder / Reports die fertig sind ?

2024-11-25 13:35 UTC, LukasStrickler commented on docs/workflows/bilderlöschung.excalidraw
Rechts sieht irgendwie falsch aus, XOR als Entscheideknoten ?
Und XOR in XOR auch unklar.

@joscha-st @Timbo003 @paulKlarer bitte auch überprüfen

2024-12-03 09:05 UTC, sternlis commented on docs/workflows/archivierungsprozess.excalidraw
@LukasStrickler Es geht um die fertigen Reports. Ich hab die jetzt mal in "Meldungen" umbenannt.

2024-12-03 09:06 UTC, sternlis commented on docs/workflows/archivierungsprozess.excalidraw
Kann auch den Zeitraum noch anpassen, 30 Tage erscheint mir recht lang, um erledigte Aufträge unarchiviert zu behalten. Aber das war das, was wir anfangs besprochen hatten.

2024-12-03 09:09 UTC, sternlis commented on docs/workflows/bilderlöschung.excalidraw
@LukasStrickler XOR, weil beides passieren kann. Es kann sowohl automatisch geschehen, als auch manuell gestartet werden. 
Der XOR nach XOR ist, weil an der Stelle der obere XOR wieder zusammengeführt wird. Man muss das ja dann wieder mit XOR zusammenführen. Kann aber zur Klarheit auch stattdessen zweimal den gleichen Endteil einfügen, anstatt des zusammenführenden XOR.

2024-12-03 09:11 UTC, sternlis commented on docs/workflows/problem-meldeprozess.excalidraw
@LukasStrickler  dadurch ist da jetzt auch ein "doppeltes" XOR wie du es oben als verwirrend fandest, habs jetzt aber mal umgesetzt.

2024-12-09 07:47 UTC, LukasStrickler requested changes

2024-12-09 07:47 UTC, LukasStrickler commented on docs/workflows/workflows.md
> +7. Bilderlöschung
nicht mehr der fall, nur valide und verlinkte bilder werden hochgeladen

2024-12-09 07:47 UTC, LukasStrickler commented on docs/workflows/bilderlöschung.excalidraw
muss removed werden, as mentioned previously

2024-12-09 08:09 UTC, joscha-st commented on docs/workflows/bilderlöschung.excalidraw
mir gefällt das auch nicht, kann mir auch nicht vorstellen das ein XOR in XOR regelkonform ist. Wäre für entweder zusätzliche Aktionen "Dialog bestätigt" o.Ä. oder aber eine Streichung der manuellen Löschung. Benötigen wir das, wenn wir nach 72h automatisch löschen? Mit dem Dialog werden wir das vermutlich ohnehin nicht implementieren.

2024-12-09 08:11 UTC, joscha-st commented on docs/workflows/problem-meldeprozess.excalidraw
Auch hier würde ich den Verlauf durch eine zusätzliche Aktion verdeutlichen

2024-12-09 08:16 UTC, joscha-st commented on docs/workflows/konto-loeschung.excalidraw
ich kann mir vorstellen, dass wir technisch Probleme bekommen, wenn wir accounts einfach löschen, macht es vielleicht Sinn hier entweder Deaktivierung zu schreiben oder "prüfung von abhängigkeiten) o.Ä..?

2024-12-09 08:18 UTC, joscha-st commented on docs/workflows/registrierung_login.excalidraw
Haben wir keine bestätigung der registrierung?

2024-12-10 09:19 UTC, joscha-st requested changes
Endereignisse sollten gemäß der HWG Lehrmeinung gestaltet werden

2024-12-10 09:51 UTC, sternlis commented on docs/workflows/konto-loeschung.excalidraw
wird in Datenbank anonymized (Mail zu "deletedUser" ändern)
Workflow löschen in: "persönliche Daten werden gelöscht"

2024-12-10 09:52 UTC, sternlis commented on docs/workflows/konto-loeschung.excalidraw
add

2024-12-10 10:00 UTC, sternlis commented on docs/workflows/problem-meldeprozess.excalidraw
mit "doppeltem" XOR wieder zusammenführen, nicht so wie jetzt direkt verbinden

2024-12-10 10:13 UTC, sternlis commented
archivierungsprozess löschen

2024-12-13 14:48 UTC, sternlis commented
Bilder Löschung Workflow löschen?

2024-12-14 11:43 UTC, paulKlarer approved these changes
Looks good

2024-12-14 15:21 UTC, LukasStrickler approved these changes

2024-12-17 08:41 UTC, joscha-st approved these changes

2024-12-17 08:41 UTC, Timbo003 approved these changes
passt

2024-12-18 13:00 UTC, merged