Create End-to-end-tests.md
LukasStrickler/FixMyTown pull request #57
Opened 2024-11-26 10:10 UTC by paulKlarer

Ich habe die End to End tests erstellt. Diese bitte reviewen.

Zustötzlich ist in [Teams](https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EbdfQnk6u91Mnk7JyisImzEBYNajvlv9TFpWNboUmwBVhQ?e=aioxIz) auch ein Word Dokument welches unsere Efforts für die Qualitätssicherung beschreibt.  Ist etwas mehr als 1 Seite. Gerne feedback auch zur länge.

2024-11-27 15:31 UTC, joscha-st commented on docs/End-to-end-tests.md
> +### Test: Das System funktioniert auf Desktop- und mobilen Geräten
wir machen eig nur web oder?

2024-11-28 13:39 UTC, paulKlarer commented on docs/End-to-end-tests.md
> +### Test: Das System funktioniert auf Desktop- und mobilen Geräten
Ich habe es umformuliert um Missverständnisse zu vermeiden.
Grundsätzlich gehe ich aber davon aus, dass unsere webseite auch von mobilen Endgeräten aufrufbar sein sollte.

2024-12-02 09:22 UTC, LukasStrickler requested changes
Admin User Stories need to be adjusted, as we do not "create accounts", but rather assign permissions via a role assignment.

2024-12-03 09:25 UTC, sternlis requested changes
- Bitte comments in Dokument einarbeiten.
- Formatierung bitte mit vorgegebenem Dokument machen.
- In Markdown (WriteUpStructure) den Qualitätssicherungsteil als geschrieben markieren.

2024-12-04 09:18 UTC, paulKlarer commented
> Admin User Stories need to be adjusted, as we do not "create accounts", but rather assign permissions via a role assignment.

In commit Anpassen der Admin E2E tests geändert

2024-12-04 11:54 UTC, paulKlarer commented
> * Bitte comments in Dokument einarbeiten.
> * Formatierung bitte mit vorgegebenem Dokument machen.
> * In Markdown (WriteUpStructure) den Qualitätssicherungsteil als geschrieben markieren.

Alles gemacht :)

2024-12-09 07:36 UTC, Timbo003 approved these changes
I’ve reviewed and everything looks solid

2024-12-09 07:52 UTC, joscha-st approved these changes
looks good

2024-12-10 09:44 UTC, paulKlarer commented
> * Bitte comments in Dokument einarbeiten.
> * Formatierung bitte mit vorgegebenem Dokument machen.
> * In Markdown (WriteUpStructure) den Qualitätssicherungsteil als geschrieben markieren.

ist geändert

2024-12-10 10:21 UTC, sternlis approved these changes

2024-12-10 10:22 UTC, merged