Report detail
LukasStrickler/FixMyTown pull request #90
Opened 2024-12-13 14:39 UTC by Timbo003

2024-12-16 14:57 UTC, LukasStrickler commented on src/server/db/schema/reports.ts
isnt the createdAt / updates at findable over the protocolls ?

2024-12-16 14:58 UTC, LukasStrickler commented on src/app/[lang]/myReports/[reportID]/page.tsx
pls move transformation logic out of return block

2024-12-16 14:58 UTC, LukasStrickler commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
remove unnecessary comments

2024-12-16 14:59 UTC, LukasStrickler requested changes
pls adjust

2024-12-18 15:32 UTC, Timbo003 commented on src/app/[lang]/myReports/[reportID]/page.tsx
did it

2024-12-18 15:33 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
sure

2024-12-18 15:37 UTC, Timbo003 commented on src/server/db/schema/reports.ts
upload works now

2024-12-28 20:11 UTC, LukasStrickler requested changes
1. Traceability of Comments and Status Changes:
Include the name of the person responsible for the comment or status change.
This ensures clear accountability and a better understanding of decision-making history.

2. Status Progression Logic:
- Avoid allowing direct transitions from new to completed; it’s poor practice.
- Implement uprank/derank logic to guide the status transitions:

Valid transitions:
- From new → in progress → completed.
- From declined → new (to reset after reconsideration).
- From completed → in progress (if rework is required).

Invalid transitions:
- Do not allow direct jumps that bypass key statuses (e.g., new → completed).

2024-12-28 20:11 UTC, LukasStrickler commented on src/components/reportDetails/reportDetails.tsx
fix linting

2024-12-28 20:11 UTC, LukasStrickler commented on src/dictionaries/de.json
fix the dict, move to correct place

2024-12-28 20:11 UTC, LukasStrickler commented on src/dictionaries/dictionary.ts
fix the dict, move to correct place

2024-12-28 20:11 UTC, LukasStrickler commented on src/dictionaries/en.json
fix the dict, move to correct place

2024-12-28 20:11 UTC, LukasStrickler commented on src/get-dictionary.ts
unecessary

2024-12-28 20:11 UTC, LukasStrickler commented on src/server/api/routers/reportDetails.ts
fix linting

./src/server/api/routers/reportDetails.ts
1:10  Warning: 'users' is defined but never used.  @typescript-eslint/no-unused-vars
2:10  Warning: 'adminProcedure' is defined but never used.  @typescript-eslint/no-unused-vars
15:24  Warning: 'ctx' is defined but never used. Allowed unused args must match /^_/u.  @typescript-eslint/no-unused-vars
59:24  Warning: 'ctx' is defined but never used. Allowed unused args must match /^_/u.  @typescript-eslint/no-unused-vars
60:17  Warning: 'reportID' is assigned a value but never used.  @typescript-eslint/no-unused-vars

2024-12-28 20:11 UTC, LukasStrickler commented on src/server/api/routers/status.ts
fix linting

./src/server/api/routers/status.ts
2:10  Warning: 'status' is defined but never used.  @typescript-eslint/no-unused-vars

2024-12-28 20:11 UTC, LukasStrickler commented on src/server/db/schema/protocoll.ts
fix linting

./src/server/db/schema/protocoll.ts
6:5  Warning: 'integer' is defined but never used.  @typescript-eslint/no-unused-vars

2024-12-28 20:11 UTC, LukasStrickler commented on src/server/db/schema/reports.ts
fix linting

./src/server/db/schema/reports.ts
2:10  Warning: 'sql' is defined but never used.  @typescript-eslint/no-unused-vars

2024-12-29 17:48 UTC, joscha-st requested changes
In general this looks good, please see comments.

2024-12-29 17:48 UTC, joscha-st commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
![image](https://github.com/user-attachments/assets/6460536b-1cff-40f3-947c-528db5dcf49a)
pls also add completed to dropdown. Once one has selected "In Progress" it's not possible to change back

2024-12-29 17:48 UTC, joscha-st commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
there seems to be some rights issue
![image](https://github.com/user-attachments/assets/f25dde29-8c93-4594-8d0a-81e93efc5cb5)
resulting in this
![image](https://github.com/user-attachments/assets/85eed62a-d4e0-49d5-be3a-228b81e661b1)

2024-12-29 17:48 UTC, joscha-st commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
> +    // You might want to add error handling here
this comment should actually be removed

2024-12-29 17:48 UTC, joscha-st commented on src/server/api/routers/reportDetails.ts
![image](https://github.com/user-attachments/assets/94c8f20e-4215-4587-be45-148e9c190ab1)
seems to be fixed

2024-12-29 18:01 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
> +    // You might want to add error handling here
added a better comment

2024-12-29 18:05 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
it works for me 
<img width="842" alt="image" src="https://github.com/user-attachments/assets/0df9d9d9-a4a7-4579-8eee-d96f8d4e7b2e" />

2024-12-29 18:07 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
i was logged in as a worker/admin
 ✓ Compiled /api/trpc/[trpc] in 207ms (2335 modules)
[TRPC] user.getUsers took 143ms to execute
 GET /api/trpc/user.getUsers?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 422ms
 
 were you logged in as a user ?

2024-12-29 18:46 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
it was the user thing, fixed it

2024-12-29 18:47 UTC, Timbo003 commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
did you reload the page ?

2024-12-29 20:06 UTC, joscha-st commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
I am sorry but this persists also after restarting the service in the current version :/ If its only an issue for me we might as well ignore it though, depending how it is for @LukasStrickler

2024-12-29 21:15 UTC, LukasStrickler commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
i am able to replicate this, but this does not seem as an "issue" for me rather maybe an ui/ux error as the status is not been sent with any other related button

what @joscha-st means is that when in a report that is in "New" status and we select "In Progress" we can not reselect "New". Then after submitting it also only shows "In Progress" this might be easily fixed by invalidating the data and causing a refetch once something is submitted. (If i refresh it shows the new options, so this is a refetch issue)

2024-12-29 21:17 UTC, LukasStrickler commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
i am also not able to find the "Declined" option from new to declined
![CleanShot 2024-12-29 at 22 17 41@2x](https://github.com/user-attachments/assets/ad599052-86f8-45ca-a277-6e32dfe0084b)

2024-12-29 21:19 UTC, LukasStrickler commented on src/app/[lang]/worker/report/details/[reportID]/page.tsx
i am not able to send comments without causing a status update, which is also connected to not showing a "disabled" button state that clearly indicates when i am allowed to submit something or not

2024-12-29 21:32 UTC, LukasStrickler requested changes

2024-12-29 21:32 UTC, LukasStrickler commented on src/app/[lang]/myReports/[reportID]/page.tsx
add multi lang support for error message
remove unnecessary comments
otherwise lgtm

2024-12-29 21:32 UTC, LukasStrickler commented on src/components/reportDetails/reportDetails.tsx
rather then hardcoding the amount of prios / status, fetch them directly from the dict and transform into a map, easier to maintain for the future

2024-12-29 21:32 UTC, LukasStrickler commented on src/components/reportDetails/workerActions.tsx
rather then hardcoding the amount of prios / status, fetch them directly from the dict and transform into a map, easier to maintain for the future

but throw error in console if this changes the amount, so that future devs know to update / check the upranking / deranking logic here

2024-12-29 21:32 UTC, LukasStrickler commented on src/server/api/routers/userRouter.ts
why is this a user procedure ?

2024-12-29 21:32 UTC, LukasStrickler commented on src/server/api/routers/status.ts
where is this used ? rather fetch directly from dict, for easier multi lang

2024-12-29 21:50 UTC, LukasStrickler requested changes

2024-12-29 21:50 UTC, LukasStrickler commented on src/server/api/routers/reportDetails.ts
you are using the wrong router, the getReportWorkerReportDetails should be used, as the other one was supposed to be used for users only

2024-12-29 21:54 UTC, LukasStrickler commented on src/server/api/routers/reportDetails.ts
this might be used to secure the user details finder

        // Find the initial protocol entry for this report to check the creator
        const initialProtocol = await db.query.protocolls.findFirst({
            where: eq(protocolls.reportId, report.id),
            orderBy: (protocolls, { asc }) => [asc(protocolls.time)]
        });

        if (!initialProtocol || initialProtocol.userId !== ctx.session.user.id) {
            throw new TRPCError({ code: 'UNAUTHORIZED', message: 'You are not authorized to view this report' });
        }

2024-12-29 21:56 UTC, LukasStrickler commented on src/server/api/routers/reportDetails.ts
lets discuss this in out meeting

2024-12-30 08:28 UTC, Timbo003 commented on src/server/api/routers/userRouter.ts
<img width="609" alt="image" src="https://github.com/user-attachments/assets/64842f0e-901d-4af6-af56-1b6ccbfa5516" />

2024-12-30 08:34 UTC, Timbo003 commented on src/server/api/routers/status.ts
this was never used. i used it in a version before and did not remove it.

its gone now.

2024-12-30 09:16 UTC, Timbo003 commented on src/components/reportDetails/workerActions.tsx
added a todo

2024-12-30 09:16 UTC, Timbo003 commented on src/components/reportDetails/reportDetails.tsx
added a todo

2024-12-30 09:19 UTC, LukasStrickler approved these changes

2024-12-30 09:19 UTC, joscha-st approved these changes

2024-12-30 09:20 UTC, merged