Fb login popup
LukasStrickler/FixMyTown pull request #92
Opened 2024-12-16 16:52 UTC by joscha-st

This implements #91
during every page display (when logged in) it is checked whether the current user has a name set and if not, a popup window is set that prompts the user to set a name.

2024-12-28 20:28 UTC, LukasStrickler requested changes
![CleanShot 2024-12-28 at 21 27 05](https://github.com/user-attachments/assets/107aa799-743c-4836-bd4c-df8bf8f0d9f7)

i have eng text when in /de/ route, pls accept my fix pr and retest if this is fixed with that

also a lot of the things here are non project standard, like using regex for validation and not zod

2024-12-28 20:28 UTC, LukasStrickler commented on src/components/namePopup.tsx
note sure but there might be exceptions necessary for the linked pages, as this triggers on the root layout mount which also effects them

as this is blocking content and requires "reading" the pages they need to be accessible without a name saved

2024-12-28 20:53 UTC, joscha-st commented on src/components/namePopup.tsx
Yes this is true. At design time these pages didn't exist, I will take a look.

2024-12-28 20:57 UTC, joscha-st commented
> ![CleanShot 2024-12-28 at 21 27 05](https://private-user-images.githubusercontent.com/145582491/399110261-107aa799-743c-4836-bd4c-df8bf8f0d9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MTgzMjksIm5iZiI6MTczNTQxODAyOSwicGF0aCI6Ii8xNDU1ODI0OTEvMzk5MTEwMjYxLTEwN2FhNzk5LTc0M2MtNDgzNi1iZDRjLWRmOGJmOGYwZDlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMDMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDAyZGFlNjdmZGI5YTNhYzRmMjgyOWZhZmU4N2ZiMTY0MjhhZGIwZjIyZmRlZGFlZGQyMDIwY2QyZmZlNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Iusgx-X8d7gSNK0RRdyRk_CD5HbpBV2gRAaTmlrrcgA)
> 
> i have eng text when in /de/ route, pls accept my fix pr and retest if this is fixed with that
> 
> also a lot of the things here are non project standard, like using regex for validation and not zod

For the language I'll try to implement your PR. Haven't seen this during testing, so you might have to validate that also

2024-12-29 19:05 UTC, joscha-st commented on src/components/namePopup.tsx
I have added this in latest commit

2024-12-29 19:19 UTC, joscha-st commented
> > ![CleanShot 2024-12-28 at 21 27 05](https://private-user-images.githubusercontent.com/145582491/399110261-107aa799-743c-4836-bd4c-df8bf8f0d9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MTgzMjksIm5iZiI6MTczNTQxODAyOSwicGF0aCI6Ii8xNDU1ODI0OTEvMzk5MTEwMjYxLTEwN2FhNzk5LTc0M2MtNDgzNi1iZDRjLWRmOGJmOGYwZDlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMDMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDAyZGFlNjdmZGI5YTNhYzRmMjgyOWZhZmU4N2ZiMTY0MjhhZGIwZjIyZmRlZGFlZGQyMDIwY2QyZmZlNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Iusgx-X8d7gSNK0RRdyRk_CD5HbpBV2gRAaTmlrrcgA)
> > i have eng text when in /de/ route, pls accept my fix pr and retest if this is fixed with that
> > also a lot of the things here are non project standard, like using regex for validation and not zod
> 
> For the language I'll try to implement your PR. Haven't seen this during testing, so you might have to validate that also.
> 
> As for "project standard" I was not aware that we have such a standard at least I feel like it was not communicated. If you have specific things I can change them

Actually, I can replicate this now (don't know when it changed) The issue persists in the sidebar as well, so it seems to be an issue with the dict. Provider. I will open a separate issue for this.
![image](https://github.com/user-attachments/assets/ff29be8d-ef05-4323-8d67-39b6e8ab5b14)

2024-12-29 20:45 UTC, LukasStrickler commented
> > ![CleanShot 2024-12-28 at 21 27 05](https://private-user-images.githubusercontent.com/145582491/399110261-107aa799-743c-4836-bd4c-df8bf8f0d9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MTgzMjksIm5iZiI6MTczNTQxODAyOSwicGF0aCI6Ii8xNDU1ODI0OTEvMzk5MTEwMjYxLTEwN2FhNzk5LTc0M2MtNDgzNi1iZDRjLWRmOGJmOGYwZDlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMDMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDAyZGFlNjdmZGI5YTNhYzRmMjgyOWZhZmU4N2ZiMTY0MjhhZGIwZjIyZmRlZGFlZGQyMDIwY2QyZmZlNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Iusgx-X8d7gSNK0RRdyRk_CD5HbpBV2gRAaTmlrrcgA)
> > i have eng text when in /de/ route, pls accept my fix pr and retest if this is fixed with that
> > also a lot of the things here are non project standard, like using regex for validation and not zod
> 
> For the language I'll try to implement your PR. Haven't seen this during testing, so you might have to validate that also.
> 
> As for "project standard" I was not aware that we have such a standard at least I feel like it was not communicated. If you have specific things I can change them

we will discuss this in our next meeting, as they have been communicated and can be found in different places in this project already!

2024-12-29 20:55 UTC, LukasStrickler requested changes

2024-12-29 20:55 UTC, LukasStrickler commented on src/components/namePopup.tsx
pls change from regex to zod and do unit test, or reuse mine to make it consistent and easier to maintain

2024-12-29 20:55 UTC, LukasStrickler commented on src/components/namePopup.tsx
with this add more descriptive error messages, how should the user know what is allowed and what not if we just say "invalid"

2024-12-29 20:55 UTC, LukasStrickler commented on src/server/api/routers/userRouter.ts
this works, but pls do not use regex for a simple min max, examples are in other routers
Or if disagreed by @Timbo003 i will be over voted and it can stay

2024-12-30 13:27 UTC, joscha-st commented on src/server/api/routers/userRouter.ts
routes will be handled in sparate PR

2024-12-30 13:28 UTC, joscha-st commented on src/components/namePopup.tsx
this has been adressed, now zod us used consistently and respective error messages are displayed

2024-12-30 13:29 UTC, joscha-st commented
With implementing the "no special characters" requirements here, I also added it to the existing name update dialogue.

2024-12-30 15:16 UTC, joscha-st commented
In adition to the implementation this does now also include testcases

2025-01-02 12:49 UTC, LukasStrickler approved these changes
lgtm

2025-01-02 12:50 UTC, merged